name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore Dependencies
      run: dotnet restore authentication-dot-net.sln
      
    - name: Build
      run: dotnet build authentication-dot-net.sln --configuration Release

    - name: Test
      run: dotnet test authentication-dot-net.sln --no-restore --verbosity minimal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: authentication-dot-net/bin
        
    - name: Archive unit-test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: UnitTests/coverage.opencover.xml



    - name: Extract coverage percentage
      id: extract_coverage
      run: |
        covered_lines=$(xmlstarlet sel -t -v "sum(//Class/Summary/SequenceCoverage/@numSequencePoints)" UnitTests/coverage.opencover.xml)
        total_lines=$(xmlstarlet sel -t -v "sum(//Class/Summary/SequenceCoverage/@coveredSequencePoints)" UnitTests/coverage.opencover.xml)
        coverage_percentage=$(awk "BEGIN { printf \"%.2f\", ($covered_lines / $total_lines) * 100 }")
        echo "::set-output name=coverage_percentage::$coverage_percentage"

    - name: Generate coverage badge
      run: |
        coverage_percentage=${{ steps.extract_coverage.outputs.coverage_percentage }}
        curl -s -o coverage-badge.svg https://img.shields.io/badge/Coverage-${coverage_percentage}%25-green
        echo "::set-output name=badge_path::coverage-badge.svg"

    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: ${{ steps.get_coverage.outputs.badge_path }}
